// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXA9bo6gBsDcI5tDk1M2KcwfQH3ncSbc',
    appId: '1:852032423968:web:fad4444e1cb31adade1445',
    messagingSenderId: '852032423968',
    projectId: 'jihc-tea-rooms',
    authDomain: 'jihc-tea-rooms.firebaseapp.com',
    storageBucket: 'jihc-tea-rooms.firebasestorage.app',
    measurementId: 'G-0DCY3BWRD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdicu2UsQRldzhEY7J1nAmaofZB3Gg2KM',
    appId: '1:852032423968:android:60a85031cda6b192de1445',
    messagingSenderId: '852032423968',
    projectId: 'jihc-tea-rooms',
    storageBucket: 'jihc-tea-rooms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoqWdLwZ5AJFsLnZy2iebXoVG9MphEqY',
    appId: '1:852032423968:ios:2a011f7f505250d5de1445',
    messagingSenderId: '852032423968',
    projectId: 'jihc-tea-rooms',
    storageBucket: 'jihc-tea-rooms.firebasestorage.app',
    iosClientId:
        '852032423968-d4pbj3ooemqi5vshntroqtr15sig18rp.apps.googleusercontent.com',
    iosBundleId: 'com.kausar.jihcTeaRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHoqWdLwZ5AJFsLnZy2iebXoVG9MphEqY',
    appId: '1:852032423968:ios:2a011f7f505250d5de1445',
    messagingSenderId: '852032423968',
    projectId: 'jihc-tea-rooms',
    storageBucket: 'jihc-tea-rooms.firebasestorage.app',
    iosClientId:
        '852032423968-d4pbj3ooemqi5vshntroqtr15sig18rp.apps.googleusercontent.com',
    iosBundleId: 'com.kausar.jihcTeaRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEXA9bo6gBsDcI5tDk1M2KcwfQH3ncSbc',
    appId: '1:852032423968:web:fad4444e1cb31adade1445',
    messagingSenderId: '852032423968',
    projectId: 'jihc-tea-rooms',
    authDomain: 'jihc-tea-rooms.firebaseapp.com',
    storageBucket: 'jihc-tea-rooms.firebasestorage.app',
    measurementId: 'G-0DCY3BWRD5',
  );
}
